name: flutter_time_tracker_app
description: A Flutter App using multiple StateManagement .


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.4
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  google_sign_in: ^5.4.2
  flutter_login_facebook: ^1.7.0
  provider: ^6.0.5
  intl: ^0.17.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/google-logo.png
    - images/facebook-logo.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
