// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUcVjxtzzZZpo7sVWDTCJtptfES64QoSs',
    appId: '1:863929157321:web:c93b86a7cb86577ab16f18',
    messagingSenderId: '863929157321',
    projectId: 'time-tracker-ee0bc',
    authDomain: 'time-tracker-ee0bc.firebaseapp.com',
    storageBucket: 'time-tracker-ee0bc.appspot.com',
    measurementId: 'G-HCDENMZJ24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLY2pxtYvjJND5D6x5kRBtrBxnhW2I7-k',
    appId: '1:863929157321:android:c0dba70d25d0f249b16f18',
    messagingSenderId: '863929157321',
    projectId: 'time-tracker-ee0bc',
    storageBucket: 'time-tracker-ee0bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7sDk-ULvhTP8DwTmdcCiPK9YLWBS7LBk',
    appId: '1:863929157321:ios:c21662b217ab6c2cb16f18',
    messagingSenderId: '863929157321',
    projectId: 'time-tracker-ee0bc',
    storageBucket: 'time-tracker-ee0bc.appspot.com',
    androidClientId: '863929157321-nao4cuevblmp8bit471cefkseuhdfng7.apps.googleusercontent.com',
    iosClientId: '863929157321-t9qocfbck5jatfvc72j2fjmt7jnhav3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTrackerApp0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7sDk-ULvhTP8DwTmdcCiPK9YLWBS7LBk',
    appId: '1:863929157321:ios:c21662b217ab6c2cb16f18',
    messagingSenderId: '863929157321',
    projectId: 'time-tracker-ee0bc',
    storageBucket: 'time-tracker-ee0bc.appspot.com',
    androidClientId: '863929157321-nao4cuevblmp8bit471cefkseuhdfng7.apps.googleusercontent.com',
    iosClientId: '863929157321-t9qocfbck5jatfvc72j2fjmt7jnhav3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTrackerApp0',
  );
}
